spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# "none" Hibernate does nothing, schema is managed externally or "validate" forces Hibernate to verify (only, doesn't do updates in schema) database tables (schema) aligned with JPA entity classes
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

logging.level.root=INFO

springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false