spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate manages database schema
spring.jpa.hibernate.ddl-auto=update

# "false" can cause hibernate.LazyInitializationException
spring.jpa.open-in-view=false

# Show Hibernate HQL query details
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=false

logging.level.root=INFO
#Show Hibernate HQL query more detailed
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true