spring.application.name=anime-tracker

logging.level.root=INFO

server.port=8080

# Makes it easier for human to read SQL logs
spring.jpa.properties.hibernate.format_sql=true
#Disabled in general to not mixing Persistence layer into Controller layer
spring.jpa.open-in-view=true
